Project lib integrations - VScode
dataiku/dss-integration-vscode pull request #26
Opened 2022-07-18 12:30 UTC by ehysi

- Add support for project libs
- Add rename/move commands to plugin content

2022-07-19 10:14 UTC, StanislasBertrand approved these changes
Works well and code LGTM ! Maybe @apichery will want to take a look as well

2022-08-28 20:02 UTC, apichery commented
Where do the icon comes from? Do we have rights to redistribute it?

2022-08-29 16:42 UTC, ehysi commented
> Where does the icon comes from? Do we have rights to redistribute it?

It comes from https://www.svgrepo.com/svg/229807/library-book . The license is CC0 which is free for commerce and redistribution. Basically a public domain license.

2022-09-21 10:16 UTC, apichery requested changes

2022-09-21 10:16 UTC, apichery commented on src/FSManager.ts
> +        let directory = "LIBRARIES/" + projectKey;
`LIBRARIES`=>`lib`

2022-09-28 11:01 UTC, merged